// flow-typed signature: 66d2e2fa3ce64e46076c4b5dea4ab96a
// flow-typed version: <<STUB>>/browserify-zlib_v^0.2.0/flow_v0.190.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'browserify-zlib'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'browserify-zlib' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'browserify-zlib/karma.conf' {
  declare module.exports: any;
}

declare module 'browserify-zlib/lib/binding' {
  declare module.exports: any;
}

declare module 'browserify-zlib/lib' {
  declare module.exports: any;
}

declare module 'browserify-zlib/src/binding' {
  declare module.exports: any;
}

declare module 'browserify-zlib/src' {
  declare module.exports: any;
}

// Filename aliases
declare module 'browserify-zlib/karma.conf.js' {
  declare module.exports: $Exports<'browserify-zlib/karma.conf'>;
}
declare module 'browserify-zlib/lib/binding.js' {
  declare module.exports: $Exports<'browserify-zlib/lib/binding'>;
}
declare module 'browserify-zlib/lib/index' {
  declare module.exports: $Exports<'browserify-zlib/lib'>;
}
declare module 'browserify-zlib/lib/index.js' {
  declare module.exports: $Exports<'browserify-zlib/lib'>;
}
declare module 'browserify-zlib/src/binding.js' {
  declare module.exports: $Exports<'browserify-zlib/src/binding'>;
}
declare module 'browserify-zlib/src/index' {
  declare module.exports: $Exports<'browserify-zlib/src'>;
}
declare module 'browserify-zlib/src/index.js' {
  declare module.exports: $Exports<'browserify-zlib/src'>;
}
