// flow-typed signature: 1f873d099f5d2da164ba45591370f3f7
// flow-typed version: <<STUB>>/web-vitals_v^3.0.3/flow_v0.190.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'web-vitals'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'web-vitals' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'web-vitals/attribution' {
  declare module.exports: any;
}

declare module 'web-vitals/base' {
  declare module.exports: any;
}

declare module 'web-vitals/dist/modules/attribution' {
  declare module.exports: any;
}

declare module 'web-vitals/dist/modules/attribution/onCLS' {
  declare module.exports: any;
}

declare module 'web-vitals/dist/modules/attribution/onFCP' {
  declare module.exports: any;
}

declare module 'web-vitals/dist/modules/attribution/onFID' {
  declare module.exports: any;
}

declare module 'web-vitals/dist/modules/attribution/onINP' {
  declare module.exports: any;
}

declare module 'web-vitals/dist/modules/attribution/onLCP' {
  declare module.exports: any;
}

declare module 'web-vitals/dist/modules/attribution/onTTFB' {
  declare module.exports: any;
}

declare module 'web-vitals/dist/modules/deprecated' {
  declare module.exports: any;
}

declare module 'web-vitals/dist/modules' {
  declare module.exports: any;
}

declare module 'web-vitals/dist/modules/lib/bfcache' {
  declare module.exports: any;
}

declare module 'web-vitals/dist/modules/lib/bindReporter' {
  declare module.exports: any;
}

declare module 'web-vitals/dist/modules/lib/generateUniqueID' {
  declare module.exports: any;
}

declare module 'web-vitals/dist/modules/lib/getActivationStart' {
  declare module.exports: any;
}

declare module 'web-vitals/dist/modules/lib/getLoadState' {
  declare module.exports: any;
}

declare module 'web-vitals/dist/modules/lib/getNavigationEntry' {
  declare module.exports: any;
}

declare module 'web-vitals/dist/modules/lib/getSelector' {
  declare module.exports: any;
}

declare module 'web-vitals/dist/modules/lib/getVisibilityWatcher' {
  declare module.exports: any;
}

declare module 'web-vitals/dist/modules/lib/initMetric' {
  declare module.exports: any;
}

declare module 'web-vitals/dist/modules/lib/observe' {
  declare module.exports: any;
}

declare module 'web-vitals/dist/modules/lib/onHidden' {
  declare module.exports: any;
}

declare module 'web-vitals/dist/modules/lib/polyfills/firstInputPolyfill' {
  declare module.exports: any;
}

declare module 'web-vitals/dist/modules/lib/polyfills/getFirstHiddenTimePolyfill' {
  declare module.exports: any;
}

declare module 'web-vitals/dist/modules/lib/polyfills/interactionCountPolyfill' {
  declare module.exports: any;
}

declare module 'web-vitals/dist/modules/onCLS' {
  declare module.exports: any;
}

declare module 'web-vitals/dist/modules/onFCP' {
  declare module.exports: any;
}

declare module 'web-vitals/dist/modules/onFID' {
  declare module.exports: any;
}

declare module 'web-vitals/dist/modules/onINP' {
  declare module.exports: any;
}

declare module 'web-vitals/dist/modules/onLCP' {
  declare module.exports: any;
}

declare module 'web-vitals/dist/modules/onTTFB' {
  declare module.exports: any;
}

declare module 'web-vitals/dist/modules/polyfill' {
  declare module.exports: any;
}

declare module 'web-vitals/dist/modules/types' {
  declare module.exports: any;
}

declare module 'web-vitals/dist/modules/types/base' {
  declare module.exports: any;
}

declare module 'web-vitals/dist/modules/types/cls' {
  declare module.exports: any;
}

declare module 'web-vitals/dist/modules/types/fcp' {
  declare module.exports: any;
}

declare module 'web-vitals/dist/modules/types/fid' {
  declare module.exports: any;
}

declare module 'web-vitals/dist/modules/types/inp' {
  declare module.exports: any;
}

declare module 'web-vitals/dist/modules/types/lcp' {
  declare module.exports: any;
}

declare module 'web-vitals/dist/modules/types/polyfills' {
  declare module.exports: any;
}

declare module 'web-vitals/dist/modules/types/ttfb' {
  declare module.exports: any;
}

declare module 'web-vitals/dist/polyfill' {
  declare module.exports: any;
}

declare module 'web-vitals/dist/web-vitals.attribution.iife' {
  declare module.exports: any;
}

declare module 'web-vitals/dist/web-vitals.attribution' {
  declare module.exports: any;
}

declare module 'web-vitals/dist/web-vitals.base.iife' {
  declare module.exports: any;
}

declare module 'web-vitals/dist/web-vitals.base' {
  declare module.exports: any;
}

declare module 'web-vitals/dist/web-vitals.iife' {
  declare module.exports: any;
}

declare module 'web-vitals/dist/web-vitals' {
  declare module.exports: any;
}

// Filename aliases
declare module 'web-vitals/attribution.js' {
  declare module.exports: $Exports<'web-vitals/attribution'>;
}
declare module 'web-vitals/base.js' {
  declare module.exports: $Exports<'web-vitals/base'>;
}
declare module 'web-vitals/dist/modules/attribution.js' {
  declare module.exports: $Exports<'web-vitals/dist/modules/attribution'>;
}
declare module 'web-vitals/dist/modules/attribution/onCLS.js' {
  declare module.exports: $Exports<'web-vitals/dist/modules/attribution/onCLS'>;
}
declare module 'web-vitals/dist/modules/attribution/onFCP.js' {
  declare module.exports: $Exports<'web-vitals/dist/modules/attribution/onFCP'>;
}
declare module 'web-vitals/dist/modules/attribution/onFID.js' {
  declare module.exports: $Exports<'web-vitals/dist/modules/attribution/onFID'>;
}
declare module 'web-vitals/dist/modules/attribution/onINP.js' {
  declare module.exports: $Exports<'web-vitals/dist/modules/attribution/onINP'>;
}
declare module 'web-vitals/dist/modules/attribution/onLCP.js' {
  declare module.exports: $Exports<'web-vitals/dist/modules/attribution/onLCP'>;
}
declare module 'web-vitals/dist/modules/attribution/onTTFB.js' {
  declare module.exports: $Exports<'web-vitals/dist/modules/attribution/onTTFB'>;
}
declare module 'web-vitals/dist/modules/deprecated.js' {
  declare module.exports: $Exports<'web-vitals/dist/modules/deprecated'>;
}
declare module 'web-vitals/dist/modules/index' {
  declare module.exports: $Exports<'web-vitals/dist/modules'>;
}
declare module 'web-vitals/dist/modules/index.js' {
  declare module.exports: $Exports<'web-vitals/dist/modules'>;
}
declare module 'web-vitals/dist/modules/lib/bfcache.js' {
  declare module.exports: $Exports<'web-vitals/dist/modules/lib/bfcache'>;
}
declare module 'web-vitals/dist/modules/lib/bindReporter.js' {
  declare module.exports: $Exports<'web-vitals/dist/modules/lib/bindReporter'>;
}
declare module 'web-vitals/dist/modules/lib/generateUniqueID.js' {
  declare module.exports: $Exports<'web-vitals/dist/modules/lib/generateUniqueID'>;
}
declare module 'web-vitals/dist/modules/lib/getActivationStart.js' {
  declare module.exports: $Exports<'web-vitals/dist/modules/lib/getActivationStart'>;
}
declare module 'web-vitals/dist/modules/lib/getLoadState.js' {
  declare module.exports: $Exports<'web-vitals/dist/modules/lib/getLoadState'>;
}
declare module 'web-vitals/dist/modules/lib/getNavigationEntry.js' {
  declare module.exports: $Exports<'web-vitals/dist/modules/lib/getNavigationEntry'>;
}
declare module 'web-vitals/dist/modules/lib/getSelector.js' {
  declare module.exports: $Exports<'web-vitals/dist/modules/lib/getSelector'>;
}
declare module 'web-vitals/dist/modules/lib/getVisibilityWatcher.js' {
  declare module.exports: $Exports<'web-vitals/dist/modules/lib/getVisibilityWatcher'>;
}
declare module 'web-vitals/dist/modules/lib/initMetric.js' {
  declare module.exports: $Exports<'web-vitals/dist/modules/lib/initMetric'>;
}
declare module 'web-vitals/dist/modules/lib/observe.js' {
  declare module.exports: $Exports<'web-vitals/dist/modules/lib/observe'>;
}
declare module 'web-vitals/dist/modules/lib/onHidden.js' {
  declare module.exports: $Exports<'web-vitals/dist/modules/lib/onHidden'>;
}
declare module 'web-vitals/dist/modules/lib/polyfills/firstInputPolyfill.js' {
  declare module.exports: $Exports<'web-vitals/dist/modules/lib/polyfills/firstInputPolyfill'>;
}
declare module 'web-vitals/dist/modules/lib/polyfills/getFirstHiddenTimePolyfill.js' {
  declare module.exports: $Exports<'web-vitals/dist/modules/lib/polyfills/getFirstHiddenTimePolyfill'>;
}
declare module 'web-vitals/dist/modules/lib/polyfills/interactionCountPolyfill.js' {
  declare module.exports: $Exports<'web-vitals/dist/modules/lib/polyfills/interactionCountPolyfill'>;
}
declare module 'web-vitals/dist/modules/onCLS.js' {
  declare module.exports: $Exports<'web-vitals/dist/modules/onCLS'>;
}
declare module 'web-vitals/dist/modules/onFCP.js' {
  declare module.exports: $Exports<'web-vitals/dist/modules/onFCP'>;
}
declare module 'web-vitals/dist/modules/onFID.js' {
  declare module.exports: $Exports<'web-vitals/dist/modules/onFID'>;
}
declare module 'web-vitals/dist/modules/onINP.js' {
  declare module.exports: $Exports<'web-vitals/dist/modules/onINP'>;
}
declare module 'web-vitals/dist/modules/onLCP.js' {
  declare module.exports: $Exports<'web-vitals/dist/modules/onLCP'>;
}
declare module 'web-vitals/dist/modules/onTTFB.js' {
  declare module.exports: $Exports<'web-vitals/dist/modules/onTTFB'>;
}
declare module 'web-vitals/dist/modules/polyfill.js' {
  declare module.exports: $Exports<'web-vitals/dist/modules/polyfill'>;
}
declare module 'web-vitals/dist/modules/types.js' {
  declare module.exports: $Exports<'web-vitals/dist/modules/types'>;
}
declare module 'web-vitals/dist/modules/types/base.js' {
  declare module.exports: $Exports<'web-vitals/dist/modules/types/base'>;
}
declare module 'web-vitals/dist/modules/types/cls.js' {
  declare module.exports: $Exports<'web-vitals/dist/modules/types/cls'>;
}
declare module 'web-vitals/dist/modules/types/fcp.js' {
  declare module.exports: $Exports<'web-vitals/dist/modules/types/fcp'>;
}
declare module 'web-vitals/dist/modules/types/fid.js' {
  declare module.exports: $Exports<'web-vitals/dist/modules/types/fid'>;
}
declare module 'web-vitals/dist/modules/types/inp.js' {
  declare module.exports: $Exports<'web-vitals/dist/modules/types/inp'>;
}
declare module 'web-vitals/dist/modules/types/lcp.js' {
  declare module.exports: $Exports<'web-vitals/dist/modules/types/lcp'>;
}
declare module 'web-vitals/dist/modules/types/polyfills.js' {
  declare module.exports: $Exports<'web-vitals/dist/modules/types/polyfills'>;
}
declare module 'web-vitals/dist/modules/types/ttfb.js' {
  declare module.exports: $Exports<'web-vitals/dist/modules/types/ttfb'>;
}
declare module 'web-vitals/dist/polyfill.js' {
  declare module.exports: $Exports<'web-vitals/dist/polyfill'>;
}
declare module 'web-vitals/dist/web-vitals.attribution.iife.js' {
  declare module.exports: $Exports<'web-vitals/dist/web-vitals.attribution.iife'>;
}
declare module 'web-vitals/dist/web-vitals.attribution.js' {
  declare module.exports: $Exports<'web-vitals/dist/web-vitals.attribution'>;
}
declare module 'web-vitals/dist/web-vitals.base.iife.js' {
  declare module.exports: $Exports<'web-vitals/dist/web-vitals.base.iife'>;
}
declare module 'web-vitals/dist/web-vitals.base.js' {
  declare module.exports: $Exports<'web-vitals/dist/web-vitals.base'>;
}
declare module 'web-vitals/dist/web-vitals.iife.js' {
  declare module.exports: $Exports<'web-vitals/dist/web-vitals.iife'>;
}
declare module 'web-vitals/dist/web-vitals.js' {
  declare module.exports: $Exports<'web-vitals/dist/web-vitals'>;
}
