// flow-typed signature: 9d47a9d2250f0ea0ee9b93fff7751d20
// flow-typed version: <<STUB>>/@babel/eslint-parser_v^7.19.1/flow_v0.190.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@babel/eslint-parser'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@babel/eslint-parser' {
  declare module.exports: any;
}
