// flow-typed signature: 0a6c98597b1d9e32b077fa0e5af60226
// flow-typed version: <<STUB>>/@babel/plugin-syntax-flow_v^7.18.6/flow_v0.190.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@babel/plugin-syntax-flow'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@babel/plugin-syntax-flow' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@babel/plugin-syntax-flow/lib' {
  declare module.exports: any;
}

// Filename aliases
declare module '@babel/plugin-syntax-flow/lib/index' {
  declare module.exports: $Exports<'@babel/plugin-syntax-flow/lib'>;
}
declare module '@babel/plugin-syntax-flow/lib/index.js' {
  declare module.exports: $Exports<'@babel/plugin-syntax-flow/lib'>;
}
